//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

<<<<<<<< HEAD:Gentleman_DuAn1_Hieu/QLThuVien/Properties/Settings.Designer.cs

<<<<<<<< HEAD:FormDangNhap/FormDangNhap/Properties/Settings.Designer.cs
namespace FormDangNhap.Properties
========
namespace QLThuVien.Properties
>>>>>>>> remotes/origin/hieu:Gentleman_DuAn1_Hieu/QLThuVien/Properties/Settings.Designer.cs
========
namespace DuAn1.Properties
>>>>>>>> remotes/origin/hung:Gentleman_DuAn1_Hung/DuAn1/Properties/Settings.Designer.cs
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }
    }
}
